// Array of randomly generated street names
module.exports = [
  "High Street",
  "Main Road",
  "Church Street",
  "Park Road",
  "Station Road",
  "Church Road",
  "Victoria Road",
  "Green Lane",
  "Queens Road",
  "London Road",
  "Mill Lane",
  "School Lane",
  "New Road",
  "The Avenue",
  "Kings Road",
  "Manor Road",
  "Hillside",
  "Grove Road",
  "Bridge Street",
  "North Street",
  "West Street",
  "East Street",
  "South Street",
  "Riverside",
  "Market Street",
  "Highfield Road",
  "Meadow Lane",
  "Beech Road",
  "Elm Street",
  "Oak Avenue",
  "Chestnut Close",
  "Willow Walk",
  "Primrose Lane",
  "Maple Drive",
  "Rosemary Lane",
  "Birch Crescent",
  "Sycamore Lane",
  "Holly Road",
  "Ivy Close",
  "Lime Avenue",
  "Acacia Grove",
  "Pine Close",
  "Juniper Way",
  "Cedar Road",
  "Blossom Street",
  "Poplar Road",
  "Fir Drive",
  "Heather Close",
  "Daisy Lane",
  "Tulip Avenue",
  "Lily Lane",
  "Violet Road",
  "Sunset Boulevard",
  "Meadow View",
  "Woodland Drive",
  "Parkside",
  "Ridge Road",
  "Valley Way",
  "Crescent Gardens",
  "Meadowcroft",
  "Brookside",
  "Dale Street",
  "Valley View",
  "Springfield",
  "Hawthorn Avenue",
  "Cherry Lane",
  "Orchard Close",
  "Willow Avenue",
  "Rosewood Drive",
  "Cotton Lane",
  "Pond View",
  "Bluebell Lane",
  "Foxglove Road",
  "Fern Walk",
  "Buttercup Close",
  "Daffodil Way",
  "Lavender Lane",
  "Honeysuckle Close",
  "Thistle Road",
  "Mossy Lane",
  "Brookside",
  "River View",
  "Greenwood Avenue",
  "Woodside Road",
  "Hazel Street",
  "Beechwood Lane",
  "Ash Close",
  "Redwood Drive",
  "Juniper Lane",
  "Cypress Road",
  "Magnolia Close",
  "Rose Lane",
  "Larkspur Lane",
  "Hawthorn Road",
  "Carnation Drive",
  "Bluebell Road",
  "Wisteria Lane",
  "Primrose Drive",
  "Sunflower Close",
  "Tulip Lane",
  "Marigold Road"
]
